config/routes.rb
FileUpload::Application.routes.draw do
  resources :uploads

  

end

app/models/upload.rb
class Upload < ActiveRecord::Base
  has_attached_file :uploaded_file, styles: { original: "4000x4000>", large: "1500x1500>", medium: "300x300>", small: "200x200>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :edit, :update, :destroy]

  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
  end

  # GET /uploads/new
  def new
    @upload = Upload.new
  end

  # GET /uploads/1/edit
  def edit
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @upload = Upload.create(upload_params)
  end

  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload.destroy
    respond_to do |format|
      format.html { redirect_to uploads_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_params
      params[:upload].permit(:uploaded_file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FileUpload</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <!-- Inclue Twitter bootstrap -->
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/uploads/_form.html.erb
<%= form_for(@upload, html: { multipart: true }) do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
        <% @upload.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.label :uploaded_file, t('.upload_new_file') %>
    <%= f.file_field :uploaded_file, multiple: true, name: 'upload[uploaded_file]' %>
    <%= f.submit %>
  </div>
<% end %>

<% # jquery upload template # %>
<script id="template-upload" type="text/x-tmpl"><div class="upload">{%=o.name%}<div class="progress"><div class="progress-bar bar" style="width: 0%"></div></div></div></script>

app/views/uploads/_upload.html.erb
<%= image_tag(@upload.uploaded_file(:small), class: 'thumb')  %>

app/views/uploads/create.js.erb
<% if @upload.new_record? %>
  alert('Failed');
<% else %>
  if ($('h1') !== undefined) {
    $('h1').append("<%=j render partial: 'uploads/upload', locals: { upload: @upload } %>");
  }
<% end %>

app/views/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<h1>Listing uploads</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @uploads.each do |upload| %>
      <tr>
        <td><%= link_to 'Show', upload %></td>
        <td><%= link_to 'Edit', edit_upload_path(upload) %></td>
        <td><%= link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Upload', new_upload_path %>

app/views/uploads/new.html.erb
<h1>New upload</h1>

<%= render 'form' %>

<%= link_to 'Back', uploads_path %>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>

<br />
<%= render 'upload' %>
<br />

<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', uploads_path %>